### ISSUE TITLE
qweather: Error on device update!

### ISSUE THREAD

**Issue by scythk** [cheny95/qweather#3]
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 736, in async_device_update
    await task
  File "/config/custom_components/qweather/weather.py", line 86, in async_update
    async with session.get(self.indices_url) as response:
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 1138, in __aenter__
    self._resp = await self._coro
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client.py", line 559, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.9/site-packages/aiohttp/client_reqrep.py", line 898, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
  File "/usr/local/lib/python3.9/site-packages/aiohttp/streams.py", line 616, in read
    await self._waiter
aiohttp.client_exceptions.ServerDisconnectedError: Server disconnected

出现问题的行好象是随机的 self.indices_url self._air_data self._hourly_data都有过
手动调用api返回的结果正常
请问可能是哪里的问题？

**Comment by cheny95** [comment]
第一确认是开发者账号，
第二可能是因为某些时候请求不通或者没有值吧。我有段时间没看了。。。

**Comment by scythk** [comment]
更新0.0.6后正常了 谢谢！
