### ISSUE TITLE
qweather在home assistant中实体注册失败，好像需要更新脚本

### ISSUE THREAD

**Issue by flying0018** [cheny95/qweather#7]
2023-03-21 10:59:51.066 WARNING (MainThread) [homeassistant.components.weather] custom_components.qweather.weather::QWeather is overriding deprecated methods on an instance of WeatherEntity, this is not valid and will be unsupported from Home Assistant 2023.1. Please report it to the custom integration author.
2023-03-21 10:59:54.396 ERROR (MainThread) [homeassistant.components.weather] qweather: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 732, in async_device_update
    await task
  File "/config/custom_components/qweather/weather.py", line 82, in async_update
    self._current = json_data["now"]
KeyError: 'now'

**Comment by cheny95** [comment]
已有热心网友修复，安装最新版。
